export const skills : Array<string> = [
    "Python",
    "Java",
    "C/C++",
    "PL/SQL",
    "JavaScript",
    "HTML",
    "CSS",
    "LATEX",
    "SpringBoot",
    "CNN",
    "ML",
    "Deep Learning",
    "AI",
    "ReactJS",
    "NodeJs",
    "Database",
    "Tensorflow",
    "AWS",
    "Azure",
    "OpenCV",
    "Django",
    "REST",
    "JSON",
    "Jira",
    "Git/Github",
    "Bitbucket",
    "Cloud Computing",
    "Matlab",
    "LeetCode",
    "Codeforces",
    "Project Management",
    "Team Management",
    "Communication Skill",
    "Leadership",
    "multi-tasking"
];
